CREATE DATABASE [CasinoStar]
GO
USE [CasinoStar]
GO
CREATE TABLE [Users]
(
  Id INT NOT NULL IDENTITY(1,1),
  Login VARCHAR(15) NOT NULL UNIQUE,
  Password VARCHAR(320) NOT NULL,
  Email VARCHAR(320) NOT NULL UNIQUE,
  Active BIT NOT NULL DEFAULT 1,
  Banned BIT NOT NULL DEFAULT 0,
  Admin BIT NOT NULL DEFAULT 0,
  Money INT NOT NULL DEFAULT 0,
  Token VARCHAR(512) UNIQUE,
  CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED
  (
    [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)
)
GO
CREATE TABLE [Roulette]
(
  Id INT NOT NULL IDENTITY(1,1),
  Date DATETIME NOT NULL DEFAULT GETDATE(),
  WinnerId INT NOT NULL,
  CONSTRAINT [PK_Roulette] PRIMARY KEY CLUSTERED
  (
    [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)
)
GO
CREATE TABLE [Blackjack]
(
  Id INT NOT NULL IDENTITY(1,1),
  Date DATETIME NOT NULL DEFAULT GETDATE(),
  WinnerId INT NOT NULL,
  CONSTRAINT [PK_Blackjack] PRIMARY KEY CLUSTERED
  (
    [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)
)
GO
ALTER TABLE [Roulette] WITH CHECK ADD CONSTRAINT [Roulette_fk0] FOREIGN KEY ([WinnerId]) REFERENCES [Users]([Id])
GO
ALTER TABLE [Blackjack] WITH CHECK ADD CONSTRAINT [Blackjack_fk0] FOREIGN KEY ([WinnerId]) REFERENCES [Users]([Id]);