USE [CasinoStar]
GO
DROP PROCEDURE InsertUser
GO
DROP PROCEDURE Users_CheckEmail
GO
DROP PROCEDURE Users_CheckLogin
GO
DROP PROCEDURE GetUser
GO
DROP PROCEDURE UpdateEmail
GO
DROP PROCEDURE UpdatePassword
GO
DROP PROCEDURE UpdateAdmin
GO
DROP PROCEDURE UpdateBanned
GO
DROP PROCEDURE UpdateActive
GO
DROP PROCEDURE RemoveUser
GO
DROP PROCEDURE GetAllUsers
GO
DROP PROCEDURE GetPassword
GO
DROP PROCEDURE VerifyUser
GO
DROP PROCEDURE SetToken